# Generated by Django 3.1.7 on 2021-02-26 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nickname", models.CharField(help_text="昵称", max_length=200, verbose_name="昵称")),
                (
                    "avatar",
                    models.URLField(
                        default="http://static.povertool.cn/avatar.png",
                        help_text="用户头像",
                        verbose_name="用户头像",
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        blank=True, default="", help_text="省", max_length=50, verbose_name="省"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, default="", help_text="市", max_length=20, verbose_name="市"
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True, default="", help_text="区县", max_length=20, verbose_name="区县"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        db_index=True,
                        help_text="手机号",
                        max_length=20,
                        unique=True,
                        verbose_name="手机号",
                    ),
                ),
                ("password", models.CharField(max_length=200)),
                ("ip", models.GenericIPAddressField()),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="创建时间", verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="更新时间", verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "用户列表",
                "ordering": ["-id"],
                "unique_together": {("phone", "nickname")},
                "index_together": {("phone", "nickname")},
            },
        ),
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="", help_text="真实姓名", max_length=50, verbose_name="真实姓名"
                    ),
                ),
                ("birthday", models.DateField(help_text="出生日期", verbose_name="出生日期")),
                ("sex", models.CharField(max_length=2)),
                ("address", models.CharField(max_length=50)),
                ("nation", models.CharField(max_length=20)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="创建时间", verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="更新时间", verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.user"),
                ),
            ],
            options={"verbose_name": "用户资料", "verbose_name_plural": "用户资料列表",},
        ),
    ]
